services:
  - type: web
    name: filmmarket-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: filmmarket_secret_2026
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 3306
      - key: OSS_REGION
        sync: false
      - key: OSS_ACCESS_KEY_ID
        sync: false
      - key: OSS_ACCESS_KEY_SECRET
        sync: false
      - key: OSS_BUCKET
        sync: false
      - key: OSS_BASE_URL
        sync: false
